-- Create schemas
CREATE SCHEMA IF NOT EXISTS finance;
CREATE SCHEMA IF NOT EXISTS reporting;

-- Grant permissions to application user
GRANT ALL PRIVILEGES ON SCHEMA finance TO app;
GRANT ALL PRIVILEGES ON SCHEMA reporting TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA finance TO app;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA reporting TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA finance GRANT ALL ON TABLES TO app;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT ALL ON TABLES TO app;
